---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-apps-setcreed-github-io-v1alpha1-dbconfig
  failurePolicy: Fail
  name: mdbconfig.kb.io
  rules:
  - apiGroups:
    - apps.setcreed.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dbconfigs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-setcreed-github-io-v1alpha1-dbconfig
  failurePolicy: Fail
  name: vdbconfig.kb.io
  rules:
  - apiGroups:
    - apps.setcreed.github.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dbconfigs
  sideEffects: None
